howlongistheline/howlongistheline.org

client/main.css
client/main.jsx
imports/api/lines.js
imports/startup/client/routes.jsx
imports/ui/Index.jsx
imports/ui/MainLayout.jsx
imports/ui/addLine.jsx
package.json

Solution: add a page to let user add line data

Problem: can't add line data

---

imports/ui/Index.jsx

solution: add an option of address in add line page

Problem: users cannot add the address for a new location

---

imports/api/lines.js
imports/startup/client/routes.jsx
imports/ui/Index.jsx
imports/ui/editLine.jsx

Solution: add a page to let user edit the location's details

Problem: can't edit location's details

---

imports/ui/Index.jsx
imports/ui/addLine.jsx
imports/ui/editLine.jsx

Solution: move the button into right position

Problem: button is moved in mobile view

---

.meteor/packages
imports/api/lines.js
imports/ui/Index.jsx
imports/ui/addLine.jsx

Solution: add a confirmation checkbox

Problem: no confirmation on add lines

---

imports/ui/Index.jsx
imports/ui/editLine.jsx
package-lock.json
package.json

remove select, add radio in editline page

---

imports/ui/Index.jsx
imports/ui/editLine.jsx
package-lock.json
package.json

Solution:
Revert gazhayes/howlongistheline.org#21

Problem: unnecessary imports, changes in general code standards

---

imports/ui/editLine.jsx

solution: move it back to center

Problem: submit button off screen on mobile

---

imports/ui/ShopDetails.jsx
package-lock.json

Solution: remove comment text after submit

Problem: comment text not cleared after submit

---

imports/ui/ShopDetails.jsx

Solution: remove the reverse function

Problem: filter is applied to status history when commenting

---

imports/ui/ShopDetails.jsx

Solution: reverse the data array

Problem: users see oldest comments first

---

imports/ui/editLine.jsx

Solution: fixed it by moving it back

Problem: button position is moved again

---

imports/api/feedback.js
imports/startup/client/routes.jsx
imports/ui/MainLayout.jsx
imports/ui/feedback.jsx
server/main.js

Problem: feedback is not implemented

---

imports/ui/MainLayout.jsx

Solution: add a github link to the sidebar

Problem: no github link

---

imports/api/lines.js

Solution: change the unit from miles to meter

Problem: distance calculation is not correct

---

imports/ui/Index.jsx
imports/ui/editLine.jsx

Solution: sort the shop array by the distance

Problem: hard to find nearest shop

---

imports/ui/Index.jsx

Solution: add a loading bar to indicate it is getting the location

Problem: list changed suddenly when user's location is found

---

imports/api/lines.js
imports/startup/client/routes.jsx
imports/ui/Index.jsx
imports/ui/ShopDetails.jsx
package-lock.json
package.json

Solution: add logic of closing time& opening time

Problem: no closing time& opening time

---

AUTHORS
imports/ui/Index.jsx

solution: replaced with "Getting your location..."
This is part of issue #54

problem: typo - "getting you location"

---

imports/ui/MainLayout.jsx

solution: update github location to the organisation instead of my personal repo

problem: wrong github location

---

.gitignore
imports/ui/Index.jsx

solution: change colour from pink to [light blue](https://www.color-hex.com/color/d9f4ff)
Solves issue #54
Also added .idea files to .gitignore

problem: search bar looks like error

---

imports/startup/client/routes.jsx
imports/ui/MainLayout.jsx
imports/ui/learntocode.jsx

solution: add links to tutorials for JS and Meteor

problem: hopeful contributors cant code yet

---

MAINTAINERS

solution: add MAINTAINERS file

problem: no list of maintainers

---

AUTHORS
client/main.html

problem: Malformed </title> end tag in /client/main.html

---

imports/ui/Index.jsx

Solution: change the text color with different line number

Problem: Visual traffic light hints are missing

---

imports/api/lines.js
imports/startup/client/routes.jsx
imports/ui/nearme.jsx

solution: find nearest stores on the server side and push the nearest 50 to the client as an array over websockets (DDP)

problem: DOM is overloaded

---

imports/ui/nearme.jsx

Solution: add a notification on top

Problem: no notification to tell user its a developing site

---

imports/ui/nearme.jsx

solution: quick and dirty page reload

problem: numbers not updating

---

imports/api/lines.js
imports/ui/editLine.jsx
imports/ui/nearme.jsx

Solution: add an edit page to let user force update the location object

Problem: can't change the location of the shops

---

imports/ui/nearme.jsx

solution: tell users to try another browser (some browsers currently being difficult)

problem: there are location errors

---

imports/ui/addLine.jsx
imports/ui/nearme.jsx

Solution: add a cancel button in adding store page

Problem: cant go back in the adding page

---

imports/api/lines.js

solution: check what kind of location object the browser is giving us and parse it based on this

problem: variance in browser location handling

---

imports/ui/nearme.jsx

solution: reduce expectations with a notice aobut the pressure we are under and what we are doing about it

problem: users expectations are too high

---

client/main.css
imports/ui/nearme.jsx

solution: set border to content instead of search box

problem: line under search box is misplaced while scroll down #93

---

imports/ui/Duplicated.jsx

Solution: fix the wrong url in duplicated

Problem: fix bugs in Depulicated

---

imports/ui/editLine.jsx

solution: let people know that we are logging their IP address and location etc

problem: some people are adding fake locations

---

imports/ui/Duplicated.jsx

solution: let people know that we name and shame malicious actors

problem: people adding fake data

---

imports/ui/nearme.jsx

problem: people are not wearing masks

---

imports/ui/nearme.jsx

solution: add button to slider

problem: people accidentally update numbers

---

imports/ui/nearme.jsx

solution: fix #125 by sending the updated variable

problem: line number not being sent to editLine

---

imports/ui/FAQ.jsx
imports/ui/editLine.jsx
imports/ui/nearme.jsx
package-lock.json

solution: change from using Onsen's Range component to using Material
UI's Slider component, with the option enabled to display the number
as a tooltip when the mouse is over the thumb on the slider.
This will display the number 0-49, or "50+".
Also fixed a couple of typos.
Fixes #94.

problem: it is tricky to determine what number the slider is on

---

README.md
build.sh
client/main.html
imports/api/lines.js
imports/ui/Duplicated.jsx
imports/ui/FAQ.jsx
imports/ui/Index_DEPRECATED.jsx
imports/ui/ShopDetails.jsx
imports/ui/addLine.jsx
imports/ui/editLine.jsx
imports/ui/feedback.jsx
imports/ui/learntocode.jsx
imports/ui/nearme.jsx

solution: fixed typos, renamed all usages of "shop" to "store"
Fixes #128

problem: typos and inconsistencies

---

imports/ui/editLine.jsx

solution: initialise it
Fixes #130

problem: Slider not initialised with value in /editLine

---

imports/ui/editLine.jsx

solution: give the store name more emphasis - bold and a bigger font.
Change the text below the slider to be more relevant
related to #132

problem: the store infocard on /editLine is unclear

---

imports/ui/editLine.jsx
imports/ui/nearme.jsx

solution: listen for touchend events as well as mouseup
Fixes #140

problem: slider doesn't work on mobile

---

imports/ui/editLine.jsx
imports/ui/nearme.jsx

solution: remove 0 and 50+
Fixes #142

problem: 0 and 50+ are superfluous now that the slider has a tooltip

---

.gitattributes

solution: include **.gitattributes** with the code below to make that to JavaScript.
```
*.css linguist-language=JavaScript
```

problem: current main language of this repoistory is CSS.

---

imports/api/lines.js
imports/startup/client/routes.jsx
imports/ui/Stocks.jsx
imports/ui/nearme.jsx

Solution: add a stock status page to let user add/check the stock status

Problem: no way to add stock status

---

imports/ui/nearme.jsx
package-lock.json
package.json

solution: added facebook and twittwe share button on each card

problem: can't share the status of a store

---

imports/ui/nearme.jsx

problem: share button text is worded slightly off

---

imports/ui/nearme.jsx

Solution: fix the missing parameter to be passed in the update button onclick function.

problem: can't update line length on mobile

---

client/main.css
imports/ui/editLine.jsx
imports/ui/nearme.jsx

solution: mark them as such so they stand out more
Fixes #138

problem: info and warning cards aren't marked as such

---

imports/api/lines.js
imports/ui/Duplicated.jsx

Solution: check the location archive for previous coordinates, render these as other choices

Problem: sometimes all locations are wrong

---

imports/api/lines.js
imports/ui/Duplicated.jsx
imports/ui/nearme.jsx

Solution: Move the location check to the client side

Problem:updating line status is very slow

---

imports/ui/nearme.jsx

solution: add a notice and dropbox link

problem: no footage for TV

---

imports/ui/nearme.jsx

solution: let the user know what's happening (loading)

Problem: line update location check can be very slow

---

server/main.js

problem: numbers become less relevant over time

---

imports/ui/addLine.jsx
imports/ui/editLine.jsx
imports/ui/nearme.jsx

Solution: add an option of high accuracy mode when fetching the user's location

Problem: location data is sometimes up to 1km off

---

imports/ui/nearme.jsx

Solution: add an expandable listitem to show the map photos

problem: not easy to see which store is where

---

client/main.css
imports/ui/nearme.jsx

solution: add a form asking businesses what problems they are having

problem: don't know what to do after lockdown

---

imports/api/lines.js
imports/ui/Stocks.jsx

Solution: allow user to mark the items are refilled

Problem:can't mark items as being back in stock

---

imports/ui/Stocks.jsx
imports/ui/nearme.jsx

problem: No sanity checks on product names; Error messages + button captions lack initial caps.
solution: Ensure product names only contain alphanumerics and spaces; Enforce a minimum length of 3 e.g. "Ice"; Capitalise messages and captions.
Partially addresses howlongistheline/howlongistheline.org#178

problem: No sanity checks on product names

---

package-lock.json
package.json
server/api/index.js
server/main.js

solution: get nearby stores api added for mobile-app

problem: no mobile app #191

---

imports/ui/Stocks.jsx

solution: changed stock page layout to reduce word count; fixed alignment; implemented cards for consistent look & feel
Fixes howlongistheline/howlongistheline.org#194

problem: stock status layout issues on Android devices

---

.meteor/packages
.meteor/versions
imports/ui/nearme.jsx

Solution: add split the search by space and do the search

Problem: search string must be 100% correct to find anything
